
language: cpp
sudo: false
dist: bionic

jobs:
  include:
    - name: "with alloc track"
      env: TRACKALLOC=1
    - name: "without alloc track"
      env: TRACKALLOC
      
install:
  - which $CXX
  - $CXX --version

script:
  - cd src && make && ./tests
