
language: cpp
sudo: false

env:
  matrix:
    #
    - INFO="with alloc track"
      TRACKALLOC=1
    #
    - INFO="without alloc track"
      TRACKALLOC=
      
install:
  - $CXX --version

script:
  - cd src && make && cd -
  - cd tests && make && ./tests
